module.exports = [
  {
    country: "Venezuela",
    crime_index: 84.49,
    safety_index: 15.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Papua New Guinea",
    crime_index: 81.93,
    safety_index: 18.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "South Africa",
    crime_index: 77.49,
    safety_index: 22.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Afghanistan",
    crime_index: 76.23,
    safety_index: 23.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Honduras",
    crime_index: 76.11,
    safety_index: 23.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Trinidad And Tobago",
    crime_index: 73.19,
    safety_index: 26.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Brazil",
    crime_index: 68.88,
    safety_index: 31.12,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Peru",
    crime_index: 68.15,
    safety_index: 31.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "El Salvador",
    crime_index: 67.96,
    safety_index: 32.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guyana",
    crime_index: 67.66,
    safety_index: 32.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Namibia",
    crime_index: 67.21,
    safety_index: 32.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Syria",
    crime_index: 66.46,
    safety_index: 33.54,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Jamaica",
    crime_index: 66.04,
    safety_index: 33.96,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Puerto Rico",
    crime_index: 65.63,
    safety_index: 34.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Angola",
    crime_index: 64.97,
    safety_index: 35.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bangladesh",
    crime_index: 63.94,
    safety_index: 36.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nigeria",
    crime_index: 63.77,
    safety_index: 36.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bahamas",
    crime_index: 62.86,
    safety_index: 37.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Libya",
    crime_index: 62.19,
    safety_index: 37.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kazakhstan",
    crime_index: 62.02,
    safety_index: 37.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Argentina",
    crime_index: 61.77,
    safety_index: 38.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kenya",
    crime_index: 61.66,
    safety_index: 38.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Dominican Republic",
    crime_index: 61.16,
    safety_index: 38.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uganda",
    crime_index: 59,
    safety_index: 41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tanzania",
    crime_index: 58.95,
    safety_index: 41.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Fiji",
    crime_index: 58.92,
    safety_index: 41.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malaysia",
    crime_index: 58.84,
    safety_index: 41.16,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Somalia",
    crime_index: 58.5,
    safety_index: 41.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mongolia",
    crime_index: 57.97,
    safety_index: 42.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guatemala",
    crime_index: 57.83,
    safety_index: 42.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Zimbabwe",
    crime_index: 57.47,
    safety_index: 42.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Costa Rica",
    crime_index: 56.33,
    safety_index: 43.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Colombia",
    crime_index: 54.79,
    safety_index: 45.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mexico",
    crime_index: 53.97,
    safety_index: 46.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uruguay",
    crime_index: 53.81,
    safety_index: 46.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Botswana",
    crime_index: 53.49,
    safety_index: 46.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Maldives",
    crime_index: 53.21,
    safety_index: 46.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bolivia",
    crime_index: 52.93,
    safety_index: 47.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ecuador",
    crime_index: 50.9,
    safety_index: 49.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cambodia",
    crime_index: 50.66,
    safety_index: 49.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Algeria",
    crime_index: 49.81,
    safety_index: 50.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Paraguay",
    crime_index: 49.6,
    safety_index: 50.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iran",
    crime_index: 49.25,
    safety_index: 50.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ethiopia",
    crime_index: 49.21,
    safety_index: 50.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ghana",
    crime_index: 48.97,
    safety_index: 51.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ukraine",
    crime_index: 48.85,
    safety_index: 51.15,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Morocco",
    crime_index: 48.69,
    safety_index: 51.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iraq",
    crime_index: 47.78,
    safety_index: 52.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mauritius",
    crime_index: 47.33,
    safety_index: 52.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United States",
    crime_index: 47.2,
    safety_index: 52.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Panama",
    crime_index: 47.19,
    safety_index: 52.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sweden",
    crime_index: 47.07,
    safety_index: 52.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Egypt",
    crime_index: 46.92,
    safety_index: 53.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "France",
    crime_index: 46.79,
    safety_index: 53.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Myanmar",
    crime_index: 45.86,
    safety_index: 54.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Indonesia",
    crime_index: 45.84,
    safety_index: 54.16,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ireland",
    crime_index: 45.43,
    safety_index: 54.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Vietnam",
    crime_index: 45.35,
    safety_index: 54.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Chile",
    crime_index: 45.23,
    safety_index: 54.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Moldova",
    crime_index: 44.98,
    safety_index: 55.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nicaragua",
    crime_index: 44.44,
    safety_index: 55.56,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Italy",
    crime_index: 44.26,
    safety_index: 55.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Pakistan",
    crime_index: 44.08,
    safety_index: 55.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belgium",
    crime_index: 43.98,
    safety_index: 56.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Kingdom",
    crime_index: 43.71,
    safety_index: 56.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Palestine",
    crime_index: 43.59,
    safety_index: 56.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lebanon",
    crime_index: 43.36,
    safety_index: 56.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "India",
    crime_index: 43.32,
    safety_index: 56.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bosnia And Herzegovina",
    crime_index: 43.03,
    safety_index: 56.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Philippines",
    crime_index: 42.16,
    safety_index: 57.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tunisia",
    crime_index: 41.88,
    safety_index: 58.12,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Australia",
    crime_index: 41.36,
    safety_index: 58.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Montenegro",
    crime_index: 41.18,
    safety_index: 58.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Russia",
    crime_index: 41.12,
    safety_index: 58.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "New Zealand",
    crime_index: 40.93,
    safety_index: 59.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Jordan",
    crime_index: 40.83,
    safety_index: 59.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Thailand",
    crime_index: 40.48,
    safety_index: 59.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Greece",
    crime_index: 40.32,
    safety_index: 59.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sri Lanka",
    crime_index: 40.22,
    safety_index: 59.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Canada",
    crime_index: 39.67,
    safety_index: 60.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Albania",
    crime_index: 39.52,
    safety_index: 60.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Turkey",
    crime_index: 39.49,
    safety_index: 60.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malta",
    crime_index: 39.04,
    safety_index: 60.96,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "North Macedonia",
    crime_index: 38.67,
    safety_index: 61.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bulgaria",
    crime_index: 38.5,
    safety_index: 61.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Serbia",
    crime_index: 37.41,
    safety_index: 62.59,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Latvia",
    crime_index: 36.95,
    safety_index: 63.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Norway",
    crime_index: 35.43,
    safety_index: 64.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hungary",
    crime_index: 35.08,
    safety_index: 64.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Germany",
    crime_index: 34.81,
    safety_index: 65.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kuwait",
    crime_index: 34.75,
    safety_index: 65.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nepal",
    crime_index: 34.56,
    safety_index: 65.44,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Luxembourg",
    crime_index: 33.39,
    safety_index: 66.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lithuania",
    crime_index: 33.06,
    safety_index: 66.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kosovo (Disputed Territory)",
    crime_index: 32.91,
    safety_index: 67.09,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Spain",
    crime_index: 31.96,
    safety_index: 68.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "China",
    crime_index: 31.83,
    safety_index: 68.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Azerbaijan",
    crime_index: 31.61,
    safety_index: 68.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Singapore",
    crime_index: 30.57,
    safety_index: 69.43,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cyprus",
    crime_index: 30.01,
    safety_index: 69.99,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Portugal",
    crime_index: 29.63,
    safety_index: 70.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Israel",
    crime_index: 29.6,
    safety_index: 70.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bahrain",
    crime_index: 29.29,
    safety_index: 70.71,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovakia",
    crime_index: 29.22,
    safety_index: 70.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Poland",
    crime_index: 28.5,
    safety_index: 71.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "South Korea",
    crime_index: 28.02,
    safety_index: 71.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Brunei",
    crime_index: 27.68,
    safety_index: 72.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Romania",
    crime_index: 27.64,
    safety_index: 72.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Netherlands",
    crime_index: 27.62,
    safety_index: 72.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cuba",
    crime_index: 27.45,
    safety_index: 72.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saudi Arabia",
    crime_index: 26.18,
    safety_index: 73.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Czech Republic",
    crime_index: 25.52,
    safety_index: 74.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Denmark",
    crime_index: 25.1,
    safety_index: 74.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belarus",
    crime_index: 24.99,
    safety_index: 75.01,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Croatia",
    crime_index: 24.71,
    safety_index: 75.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Austria",
    crime_index: 23.73,
    safety_index: 76.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iceland",
    crime_index: 23.36,
    safety_index: 76.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Finland",
    crime_index: 23.32,
    safety_index: 76.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Estonia",
    crime_index: 23.14,
    safety_index: 76.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Armenia",
    crime_index: 21.6,
    safety_index: 78.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Switzerland",
    crime_index: 21.6,
    safety_index: 78.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovenia",
    crime_index: 21.07,
    safety_index: 78.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Oman",
    crime_index: 20.79,
    safety_index: 79.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hong Kong",
    crime_index: 20.7,
    safety_index: 79.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Japan",
    crime_index: 20.66,
    safety_index: 79.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Georgia",
    crime_index: 20.21,
    safety_index: 79.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Arab Emirates",
    crime_index: 15.7,
    safety_index: 84.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Taiwan",
    crime_index: 15.65,
    safety_index: 84.35,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Qatar",
    crime_index: 11.86,
    safety_index: 88.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
].map((data, i) => {
  data.id = i + 1;
  return data;
});
