module.exports = [
  {
    country: "Afghanistan",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 700,
    literacy: 36,
    phones: 3.2,
    climate: 1,
    birthrate: 46.6,
    deathrate: 20.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Albania",
    region: "EASTERN EUROPE",
    gdp: 4500,
    literacy: 86.5,
    phones: 71.2,
    climate: 3,
    birthrate: 15.11,
    deathrate: 5.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Algeria",
    region: "NORTHERN AFRICA",
    gdp: 6000,
    literacy: 70,
    phones: 78.1,
    climate: 1,
    birthrate: 17.14,
    deathrate: 4.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "American Samoa",
    region: "OCEANIA",
    gdp: 8000,
    literacy: 97,
    phones: 259.5,
    climate: 2,
    birthrate: 22.46,
    deathrate: 3.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Andorra",
    region: "WESTERN EUROPE",
    gdp: 19000,
    literacy: 100,
    phones: 497.2,
    climate: 3,
    birthrate: 8.71,
    deathrate: 6.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Angola",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1900,
    literacy: 42,
    phones: 7.8,
    climate: 0,
    birthrate: 45.11,
    deathrate: 24.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Anguilla",
    region: "LATIN AMER. & CARIB",
    gdp: 8600,
    literacy: 95,
    phones: 460,
    climate: 2,
    birthrate: 14.17,
    deathrate: 5.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Antigua & Barbuda",
    region: "LATIN AMER. & CARIB",
    gdp: 11000,
    literacy: 89,
    phones: 549.9,
    climate: 2,
    birthrate: 16.93,
    deathrate: 5.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Argentina",
    region: "LATIN AMER. & CARIB",
    gdp: 11200,
    literacy: 97.1,
    phones: 220.4,
    climate: 3,
    birthrate: 16.73,
    deathrate: 7.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Armenia",
    region: "C.W. OF IND. STATES",
    gdp: 3500,
    literacy: 98.6,
    phones: 195.7,
    climate: 4,
    birthrate: 12.07,
    deathrate: 8.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Aruba",
    region: "LATIN AMER. & CARIB",
    gdp: 28000,
    literacy: 97,
    phones: 516.1,
    climate: 2,
    birthrate: 11.03,
    deathrate: 6.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Australia",
    region: "OCEANIA",
    gdp: 29000,
    literacy: 100,
    phones: 565.5,
    climate: 1,
    birthrate: 12.14,
    deathrate: 7.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Austria",
    region: "WESTERN EUROPE",
    gdp: 30000,
    literacy: 98,
    phones: 452.2,
    climate: 3,
    birthrate: 8.74,
    deathrate: 9.76,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Azerbaijan",
    region: "C.W. OF IND. STATES",
    gdp: 3400,
    literacy: 97,
    phones: 137.1,
    climate: 1,
    birthrate: 20.74,
    deathrate: 9.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bahamas, The",
    region: "LATIN AMER. & CARIB",
    gdp: 16700,
    literacy: 95.6,
    phones: 460.6,
    climate: 2,
    birthrate: 17.57,
    deathrate: 9.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bahrain",
    region: "NEAR EAST",
    gdp: 16900,
    literacy: 89.1,
    phones: 281.3,
    climate: 1,
    birthrate: 17.8,
    deathrate: 4.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bangladesh",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1900,
    literacy: 43.1,
    phones: 7.3,
    climate: 2,
    birthrate: 29.8,
    deathrate: 8.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Barbados",
    region: "LATIN AMER. & CARIB",
    gdp: 15700,
    literacy: 97.4,
    phones: 481.9,
    climate: 2,
    birthrate: 12.71,
    deathrate: 8.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belarus",
    region: "C.W. OF IND. STATES",
    gdp: 6100,
    literacy: 99.6,
    phones: 319.1,
    climate: 4,
    birthrate: 11.16,
    deathrate: 14.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belgium",
    region: "WESTERN EUROPE",
    gdp: 29100,
    literacy: 98,
    phones: 462.6,
    climate: 3,
    birthrate: 10.38,
    deathrate: 10.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belize",
    region: "LATIN AMER. & CARIB",
    gdp: 4900,
    literacy: 94.1,
    phones: 115.7,
    climate: 2,
    birthrate: 28.84,
    deathrate: 5.72,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Benin",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1100,
    literacy: 40.9,
    phones: 9.7,
    climate: 2,
    birthrate: 38.85,
    deathrate: 12.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bermuda",
    region: "NORTHERN AMERICA",
    gdp: 36000,
    literacy: 98,
    phones: 851.4,
    climate: 2,
    birthrate: 11.4,
    deathrate: 7.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bhutan",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1300,
    literacy: 42.2,
    phones: 14.3,
    climate: 2,
    birthrate: 33.65,
    deathrate: 12.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bolivia",
    region: "LATIN AMER. & CARIB",
    gdp: 2400,
    literacy: 87.2,
    phones: 71.9,
    climate: 1.5,
    birthrate: 23.3,
    deathrate: 7.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bosnia & Herzegovina",
    region: "EASTERN EUROPE",
    gdp: 6100,
    literacy: 0,
    phones: 215.4,
    climate: 4,
    birthrate: 8.77,
    deathrate: 8.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Botswana",
    region: "SUB-SAHARAN AFRICA",
    gdp: 9000,
    literacy: 79.8,
    phones: 80.5,
    climate: 1,
    birthrate: 23.08,
    deathrate: 29.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Brazil",
    region: "LATIN AMER. & CARIB",
    gdp: 7600,
    literacy: 86.4,
    phones: 225.3,
    climate: 2,
    birthrate: 16.56,
    deathrate: 6.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "British Virgin Is.",
    region: "LATIN AMER. & CARIB",
    gdp: 16000,
    literacy: 97.8,
    phones: 506.5,
    climate: 2,
    birthrate: 14.89,
    deathrate: 4.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Brunei",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 18600,
    literacy: 93.9,
    phones: 237.2,
    climate: 2,
    birthrate: 18.79,
    deathrate: 3.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bulgaria",
    region: "EASTERN EUROPE",
    gdp: 7600,
    literacy: 98.6,
    phones: 336.3,
    climate: 3,
    birthrate: 9.65,
    deathrate: 14.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Burkina Faso",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1100,
    literacy: 26.6,
    phones: 7,
    climate: 2,
    birthrate: 45.62,
    deathrate: 15.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Burma",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1800,
    literacy: 85.3,
    phones: 10.1,
    climate: 2,
    birthrate: 17.91,
    deathrate: 9.83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Burundi",
    region: "SUB-SAHARAN AFRICA",
    gdp: 600,
    literacy: 51.6,
    phones: 3.4,
    climate: 2,
    birthrate: 42.22,
    deathrate: 13.46,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cambodia",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1900,
    literacy: 69.4,
    phones: 2.6,
    climate: 2,
    birthrate: 26.9,
    deathrate: 9.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cameroon",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1800,
    literacy: 79,
    phones: 5.7,
    climate: 1.5,
    birthrate: 33.89,
    deathrate: 13.47,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Canada",
    region: "NORTHERN AMERICA",
    gdp: 29800,
    literacy: 97,
    phones: 552.2,
    climate: 0,
    birthrate: 10.78,
    deathrate: 7.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cape Verde",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1400,
    literacy: 76.6,
    phones: 169.6,
    climate: 3,
    birthrate: 24.87,
    deathrate: 6.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cayman Islands",
    region: "LATIN AMER. & CARIB",
    gdp: 35000,
    literacy: 98,
    phones: 836.3,
    climate: 2,
    birthrate: 12.74,
    deathrate: 4.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Central African Rep.",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1100,
    literacy: 51,
    phones: 2.3,
    climate: 2,
    birthrate: 33.91,
    deathrate: 18.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Chad",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1200,
    literacy: 47.5,
    phones: 1.3,
    climate: 2,
    birthrate: 45.73,
    deathrate: 16.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Chile",
    region: "LATIN AMER. & CARIB",
    gdp: 9900,
    literacy: 96.2,
    phones: 213,
    climate: 3,
    birthrate: 15.23,
    deathrate: 5.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "China",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 5000,
    literacy: 90.9,
    phones: 266.7,
    climate: 1.5,
    birthrate: 13.25,
    deathrate: 6.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Colombia",
    region: "LATIN AMER. & CARIB",
    gdp: 6300,
    literacy: 92.5,
    phones: 176.2,
    climate: 2,
    birthrate: 20.48,
    deathrate: 5.58,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Comoros",
    region: "SUB-SAHARAN AFRICA",
    gdp: 700,
    literacy: 56.5,
    phones: 24.5,
    climate: 2,
    birthrate: 36.93,
    deathrate: 8.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Congo, Dem. Rep.",
    region: "SUB-SAHARAN AFRICA",
    gdp: 700,
    literacy: 65.5,
    phones: 0.2,
    climate: 2,
    birthrate: 43.69,
    deathrate: 13.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Congo, Repub. of the",
    region: "SUB-SAHARAN AFRICA",
    gdp: 700,
    literacy: 83.8,
    phones: 3.7,
    climate: 2,
    birthrate: 42.57,
    deathrate: 12.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cook Islands",
    region: "OCEANIA",
    gdp: 5000,
    literacy: 95,
    phones: 289.9,
    climate: 2,
    birthrate: 21,
    deathrate: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Costa Rica",
    region: "LATIN AMER. & CARIB",
    gdp: 9100,
    literacy: 96,
    phones: 340.7,
    climate: 2,
    birthrate: 18.32,
    deathrate: 4.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cote d'Ivoire",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1400,
    literacy: 50.9,
    phones: 14.6,
    climate: 2,
    birthrate: 35.11,
    deathrate: 14.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Croatia",
    region: "EASTERN EUROPE",
    gdp: 10600,
    literacy: 98.5,
    phones: 420.4,
    climate: 0,
    birthrate: 9.61,
    deathrate: 11.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cuba",
    region: "LATIN AMER. & CARIB",
    gdp: 2900,
    literacy: 97,
    phones: 74.7,
    climate: 2,
    birthrate: 11.89,
    deathrate: 7.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cyprus",
    region: "NEAR EAST",
    gdp: 19200,
    literacy: 97.6,
    phones: 0,
    climate: 3,
    birthrate: 12.56,
    deathrate: 7.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Czech Republic",
    region: "EASTERN EUROPE",
    gdp: 15700,
    literacy: 99.9,
    phones: 314.3,
    climate: 3,
    birthrate: 9.02,
    deathrate: 10.59,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Denmark",
    region: "WESTERN EUROPE",
    gdp: 31100,
    literacy: 100,
    phones: 614.6,
    climate: 3,
    birthrate: 11.13,
    deathrate: 10.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Djibouti",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1300,
    literacy: 67.9,
    phones: 22.8,
    climate: 1,
    birthrate: 39.53,
    deathrate: 19.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Dominica",
    region: "LATIN AMER. & CARIB",
    gdp: 5400,
    literacy: 94,
    phones: 304.8,
    climate: 2,
    birthrate: 15.27,
    deathrate: 6.73,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Dominican Republic",
    region: "LATIN AMER. & CARIB",
    gdp: 6000,
    literacy: 84.7,
    phones: 97.4,
    climate: 2,
    birthrate: 23.22,
    deathrate: 5.73,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "East Timor",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 500,
    literacy: 58.6,
    phones: 0,
    climate: 2,
    birthrate: 26.99,
    deathrate: 6.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ecuador",
    region: "LATIN AMER. & CARIB",
    gdp: 3300,
    literacy: 92.5,
    phones: 125.6,
    climate: 2,
    birthrate: 22.29,
    deathrate: 4.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Egypt",
    region: "NORTHERN AFRICA",
    gdp: 4000,
    literacy: 57.7,
    phones: 131.8,
    climate: 1,
    birthrate: 22.94,
    deathrate: 5.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "El Salvador",
    region: "LATIN AMER. & CARIB",
    gdp: 4800,
    literacy: 80.2,
    phones: 142.4,
    climate: 2,
    birthrate: 26.61,
    deathrate: 5.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Equatorial Guinea",
    region: "SUB-SAHARAN AFRICA",
    gdp: 2700,
    literacy: 85.7,
    phones: 18.5,
    climate: 2,
    birthrate: 35.59,
    deathrate: 15.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Eritrea",
    region: "SUB-SAHARAN AFRICA",
    gdp: 700,
    literacy: 58.6,
    phones: 7.9,
    climate: 1.5,
    birthrate: 34.33,
    deathrate: 9.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Estonia",
    region: "BALTICS",
    gdp: 12300,
    literacy: 99.8,
    phones: 333.8,
    climate: 3,
    birthrate: 10.04,
    deathrate: 13.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ethiopia",
    region: "SUB-SAHARAN AFRICA",
    gdp: 700,
    literacy: 42.7,
    phones: 8.2,
    climate: 2,
    birthrate: 37.98,
    deathrate: 14.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Faroe Islands",
    region: "WESTERN EUROPE",
    gdp: 22000,
    literacy: 0,
    phones: 503.8,
    climate: 0,
    birthrate: 14.05,
    deathrate: 8.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Fiji",
    region: "OCEANIA",
    gdp: 5800,
    literacy: 93.7,
    phones: 112.6,
    climate: 2,
    birthrate: 22.55,
    deathrate: 5.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Finland",
    region: "WESTERN EUROPE",
    gdp: 27400,
    literacy: 100,
    phones: 405.3,
    climate: 3,
    birthrate: 10.45,
    deathrate: 9.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "France",
    region: "WESTERN EUROPE",
    gdp: 27600,
    literacy: 99,
    phones: 586.4,
    climate: 4,
    birthrate: 11.99,
    deathrate: 9.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "French Guiana",
    region: "LATIN AMER. & CARIB",
    gdp: 8300,
    literacy: 83,
    phones: 255.6,
    climate: 2,
    birthrate: 20.46,
    deathrate: 4.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "French Polynesia",
    region: "OCEANIA",
    gdp: 17500,
    literacy: 98,
    phones: 194.5,
    climate: 2,
    birthrate: 16.68,
    deathrate: 4.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Gabon",
    region: "SUB-SAHARAN AFRICA",
    gdp: 5500,
    literacy: 63.2,
    phones: 27.4,
    climate: 2,
    birthrate: 36.16,
    deathrate: 12.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Gambia, The",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1700,
    literacy: 40.1,
    phones: 26.8,
    climate: 2,
    birthrate: 39.37,
    deathrate: 12.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Gaza Strip",
    region: "NEAR EAST",
    gdp: 600,
    literacy: 0,
    phones: 244.3,
    climate: 3,
    birthrate: 39.45,
    deathrate: 3.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Georgia",
    region: "C.W. OF IND. STATES",
    gdp: 2500,
    literacy: 99,
    phones: 146.6,
    climate: 3,
    birthrate: 10.41,
    deathrate: 9.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Germany",
    region: "WESTERN EUROPE",
    gdp: 27600,
    literacy: 99,
    phones: 667.9,
    climate: 3,
    birthrate: 8.25,
    deathrate: 10.62,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ghana",
    region: "SUB-SAHARAN AFRICA",
    gdp: 2200,
    literacy: 74.8,
    phones: 14.4,
    climate: 2,
    birthrate: 30.52,
    deathrate: 9.72,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Gibraltar",
    region: "WESTERN EUROPE",
    gdp: 17500,
    literacy: 0,
    phones: 877.7,
    climate: 0,
    birthrate: 10.74,
    deathrate: 9.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Greece",
    region: "WESTERN EUROPE",
    gdp: 20000,
    literacy: 97.5,
    phones: 589.7,
    climate: 3,
    birthrate: 9.68,
    deathrate: 10.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Greenland",
    region: "NORTHERN AMERICA",
    gdp: 20000,
    literacy: 0,
    phones: 448.9,
    climate: 1,
    birthrate: 15.93,
    deathrate: 7.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Grenada",
    region: "LATIN AMER. & CARIB",
    gdp: 5000,
    literacy: 98,
    phones: 364.5,
    climate: 2,
    birthrate: 22.08,
    deathrate: 6.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guadeloupe",
    region: "LATIN AMER. & CARIB",
    gdp: 8000,
    literacy: 90,
    phones: 463.8,
    climate: 2,
    birthrate: 15.05,
    deathrate: 6.09,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guam",
    region: "OCEANIA",
    gdp: 21000,
    literacy: 99,
    phones: 492,
    climate: 2,
    birthrate: 18.79,
    deathrate: 4.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guatemala",
    region: "LATIN AMER. & CARIB",
    gdp: 4100,
    literacy: 70.6,
    phones: 92.1,
    climate: 2,
    birthrate: 29.88,
    deathrate: 5.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guernsey",
    region: "WESTERN EUROPE",
    gdp: 20000,
    literacy: 0,
    phones: 842.4,
    climate: 3,
    birthrate: 8.81,
    deathrate: 10.01,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guinea",
    region: "SUB-SAHARAN AFRICA",
    gdp: 2100,
    literacy: 35.9,
    phones: 2.7,
    climate: 2,
    birthrate: 41.76,
    deathrate: 15.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guinea-Bissau",
    region: "SUB-SAHARAN AFRICA",
    gdp: 800,
    literacy: 42.4,
    phones: 7.4,
    climate: 2,
    birthrate: 37.22,
    deathrate: 16.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guyana",
    region: "LATIN AMER. & CARIB",
    gdp: 4000,
    literacy: 98.8,
    phones: 143.5,
    climate: 2,
    birthrate: 18.28,
    deathrate: 8.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Haiti",
    region: "LATIN AMER. & CARIB",
    gdp: 1600,
    literacy: 52.9,
    phones: 16.9,
    climate: 2,
    birthrate: 36.44,
    deathrate: 12.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Honduras",
    region: "LATIN AMER. & CARIB",
    gdp: 2600,
    literacy: 76.2,
    phones: 67.5,
    climate: 2,
    birthrate: 28.24,
    deathrate: 5.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hong Kong",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 28800,
    literacy: 93.5,
    phones: 546.7,
    climate: 2,
    birthrate: 7.29,
    deathrate: 6.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hungary",
    region: "EASTERN EUROPE",
    gdp: 13900,
    literacy: 99.4,
    phones: 336.2,
    climate: 3,
    birthrate: 9.72,
    deathrate: 13.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iceland",
    region: "WESTERN EUROPE",
    gdp: 30900,
    literacy: 99.9,
    phones: 647.7,
    climate: 3,
    birthrate: 13.64,
    deathrate: 6.72,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "India",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 2900,
    literacy: 59.5,
    phones: 45.4,
    climate: 2.5,
    birthrate: 22.01,
    deathrate: 8.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Indonesia",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 3200,
    literacy: 87.9,
    phones: 52,
    climate: 2,
    birthrate: 20.34,
    deathrate: 6.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iran",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 7000,
    literacy: 79.4,
    phones: 276.4,
    climate: 1,
    birthrate: 17,
    deathrate: 5.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iraq",
    region: "NEAR EAST",
    gdp: 1500,
    literacy: 40.4,
    phones: 38.6,
    climate: 1,
    birthrate: 31.98,
    deathrate: 5.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ireland",
    region: "WESTERN EUROPE",
    gdp: 29600,
    literacy: 98,
    phones: 500.5,
    climate: 3,
    birthrate: 14.45,
    deathrate: 7.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Isle of Man",
    region: "WESTERN EUROPE",
    gdp: 21000,
    literacy: 0,
    phones: 676,
    climate: 3,
    birthrate: 11.05,
    deathrate: 11.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Israel",
    region: "NEAR EAST",
    gdp: 19800,
    literacy: 95.4,
    phones: 462.3,
    climate: 3,
    birthrate: 17.97,
    deathrate: 6.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Italy",
    region: "WESTERN EUROPE",
    gdp: 26700,
    literacy: 98.6,
    phones: 430.9,
    climate: 0,
    birthrate: 8.72,
    deathrate: 10.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Jamaica",
    region: "LATIN AMER. & CARIB",
    gdp: 3900,
    literacy: 87.9,
    phones: 124,
    climate: 2,
    birthrate: 20.82,
    deathrate: 6.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Japan",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 28200,
    literacy: 99,
    phones: 461.2,
    climate: 3,
    birthrate: 9.37,
    deathrate: 9.16,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Jersey",
    region: "WESTERN EUROPE",
    gdp: 24800,
    literacy: 0,
    phones: 811.3,
    climate: 3,
    birthrate: 9.3,
    deathrate: 9.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Jordan",
    region: "NEAR EAST",
    gdp: 4300,
    literacy: 91.3,
    phones: 104.5,
    climate: 1,
    birthrate: 21.25,
    deathrate: 2.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kazakhstan",
    region: "C.W. OF IND. STATES",
    gdp: 6300,
    literacy: 98.4,
    phones: 164.1,
    climate: 4,
    birthrate: 16,
    deathrate: 9.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kenya",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1000,
    literacy: 85.1,
    phones: 8.1,
    climate: 1.5,
    birthrate: 39.72,
    deathrate: 14.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kiribati",
    region: "OCEANIA",
    gdp: 800,
    literacy: 0,
    phones: 42.7,
    climate: 2,
    birthrate: 30.65,
    deathrate: 8.26,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Korea, North",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1300,
    literacy: 99,
    phones: 42.4,
    climate: 3,
    birthrate: 15.54,
    deathrate: 7.13,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Korea, South",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 17800,
    literacy: 97.9,
    phones: 486.1,
    climate: 3,
    birthrate: 10,
    deathrate: 5.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kuwait",
    region: "NEAR EAST",
    gdp: 19000,
    literacy: 83.5,
    phones: 211,
    climate: 1,
    birthrate: 21.94,
    deathrate: 2.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kyrgyzstan",
    region: "C.W. OF IND. STATES",
    gdp: 1600,
    literacy: 97,
    phones: 84,
    climate: 2.5,
    birthrate: 22.8,
    deathrate: 7.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Laos",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1700,
    literacy: 66.4,
    phones: 14.1,
    climate: 2,
    birthrate: 35.49,
    deathrate: 11.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Latvia",
    region: "BALTICS",
    gdp: 10200,
    literacy: 99.8,
    phones: 321.4,
    climate: 3,
    birthrate: 9.24,
    deathrate: 13.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lebanon",
    region: "NEAR EAST",
    gdp: 4800,
    literacy: 87.4,
    phones: 255.6,
    climate: 0,
    birthrate: 18.52,
    deathrate: 6.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lesotho",
    region: "SUB-SAHARAN AFRICA",
    gdp: 3000,
    literacy: 84.8,
    phones: 23.7,
    climate: 3,
    birthrate: 24.75,
    deathrate: 28.71,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Liberia",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1000,
    literacy: 57.5,
    phones: 2.3,
    climate: 2,
    birthrate: 44.77,
    deathrate: 23.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Libya",
    region: "NORTHERN AFRICA",
    gdp: 6400,
    literacy: 82.6,
    phones: 127.1,
    climate: 0,
    birthrate: 26.49,
    deathrate: 3.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Liechtenstein",
    region: "WESTERN EUROPE",
    gdp: 25000,
    literacy: 100,
    phones: 585.5,
    climate: 4,
    birthrate: 10.21,
    deathrate: 7.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lithuania",
    region: "BALTICS",
    gdp: 11400,
    literacy: 99.6,
    phones: 223.4,
    climate: 0,
    birthrate: 8.75,
    deathrate: 10.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Luxembourg",
    region: "WESTERN EUROPE",
    gdp: 55100,
    literacy: 100,
    phones: 515.4,
    climate: 0,
    birthrate: 11.94,
    deathrate: 8.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Macau",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 19400,
    literacy: 94.5,
    phones: 384.9,
    climate: 2,
    birthrate: 8.48,
    deathrate: 4.47,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Macedonia",
    region: "EASTERN EUROPE",
    gdp: 6700,
    literacy: 0,
    phones: 260,
    climate: 3,
    birthrate: 12.02,
    deathrate: 8.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Madagascar",
    region: "SUB-SAHARAN AFRICA",
    gdp: 800,
    literacy: 68.9,
    phones: 3.6,
    climate: 2,
    birthrate: 41.41,
    deathrate: 11.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malawi",
    region: "SUB-SAHARAN AFRICA",
    gdp: 600,
    literacy: 62.7,
    phones: 7.9,
    climate: 2,
    birthrate: 43.13,
    deathrate: 19.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malaysia",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 9000,
    literacy: 88.7,
    phones: 179,
    climate: 2,
    birthrate: 22.86,
    deathrate: 5.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Maldives",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 3900,
    literacy: 97.2,
    phones: 90,
    climate: 2,
    birthrate: 34.81,
    deathrate: 7.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mali",
    region: "SUB-SAHARAN AFRICA",
    gdp: 900,
    literacy: 46.4,
    phones: 6.4,
    climate: 2,
    birthrate: 49.82,
    deathrate: 16.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malta",
    region: "WESTERN EUROPE",
    gdp: 17700,
    literacy: 92.8,
    phones: 505,
    climate: 0,
    birthrate: 10.22,
    deathrate: 8.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Marshall Islands",
    region: "OCEANIA",
    gdp: 1600,
    literacy: 93.7,
    phones: 91.2,
    climate: 2,
    birthrate: 33.05,
    deathrate: 4.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Martinique",
    region: "LATIN AMER. & CARIB",
    gdp: 14400,
    literacy: 97.7,
    phones: 394.4,
    climate: 2,
    birthrate: 13.74,
    deathrate: 6.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mauritania",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1800,
    literacy: 41.7,
    phones: 12.9,
    climate: 1,
    birthrate: 40.99,
    deathrate: 12.16,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mauritius",
    region: "SUB-SAHARAN AFRICA",
    gdp: 11400,
    literacy: 85.6,
    phones: 289.3,
    climate: 2,
    birthrate: 15.43,
    deathrate: 6.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mayotte",
    region: "SUB-SAHARAN AFRICA",
    gdp: 2600,
    literacy: 0,
    phones: 49.7,
    climate: 2,
    birthrate: 40.95,
    deathrate: 7.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mexico",
    region: "LATIN AMER. & CARIB",
    gdp: 9000,
    literacy: 92.2,
    phones: 181.6,
    climate: 1.5,
    birthrate: 20.69,
    deathrate: 4.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Micronesia, Fed. St.",
    region: "OCEANIA",
    gdp: 2000,
    literacy: 89,
    phones: 114.8,
    climate: 2,
    birthrate: 24.68,
    deathrate: 4.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Moldova",
    region: "C.W. OF IND. STATES",
    gdp: 1800,
    literacy: 99.1,
    phones: 208.1,
    climate: 0,
    birthrate: 15.7,
    deathrate: 12.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Monaco",
    region: "WESTERN EUROPE",
    gdp: 27000,
    literacy: 99,
    phones: 1035.6,
    climate: 0,
    birthrate: 9.19,
    deathrate: 12.91,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mongolia",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1800,
    literacy: 97.8,
    phones: 55.1,
    climate: 1,
    birthrate: 21.59,
    deathrate: 6.95,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Montserrat",
    region: "LATIN AMER. & CARIB",
    gdp: 3400,
    literacy: 97,
    phones: 0,
    climate: 2,
    birthrate: 17.59,
    deathrate: 7.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Morocco",
    region: "NORTHERN AFRICA",
    gdp: 4000,
    literacy: 51.7,
    phones: 40.4,
    climate: 0,
    birthrate: 21.98,
    deathrate: 5.58,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mozambique",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1200,
    literacy: 47.8,
    phones: 3.5,
    climate: 2,
    birthrate: 35.18,
    deathrate: 21.35,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Namibia",
    region: "SUB-SAHARAN AFRICA",
    gdp: 7200,
    literacy: 84,
    phones: 62.6,
    climate: 1,
    birthrate: 24.32,
    deathrate: 18.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nauru",
    region: "OCEANIA",
    gdp: 5000,
    literacy: 0,
    phones: 143,
    climate: 2,
    birthrate: 24.76,
    deathrate: 6.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nepal",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 1400,
    literacy: 45.2,
    phones: 15.9,
    climate: 0,
    birthrate: 30.98,
    deathrate: 9.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Netherlands",
    region: "WESTERN EUROPE",
    gdp: 28600,
    literacy: 99,
    phones: 460.8,
    climate: 3,
    birthrate: 10.9,
    deathrate: 8.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Netherlands Antilles",
    region: "LATIN AMER. & CARIB",
    gdp: 11400,
    literacy: 96.7,
    phones: 365.3,
    climate: 2,
    birthrate: 14.78,
    deathrate: 6.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "New Caledonia",
    region: "OCEANIA",
    gdp: 15000,
    literacy: 91,
    phones: 252.2,
    climate: 2,
    birthrate: 18.11,
    deathrate: 5.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "New Zealand",
    region: "OCEANIA",
    gdp: 21600,
    literacy: 99,
    phones: 441.7,
    climate: 3,
    birthrate: 13.76,
    deathrate: 7.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nicaragua",
    region: "LATIN AMER. & CARIB",
    gdp: 2300,
    literacy: 67.5,
    phones: 39.7,
    climate: 2,
    birthrate: 24.51,
    deathrate: 4.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Niger",
    region: "SUB-SAHARAN AFRICA",
    gdp: 800,
    literacy: 17.6,
    phones: 1.9,
    climate: 1,
    birthrate: 50.73,
    deathrate: 20.91,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nigeria",
    region: "SUB-SAHARAN AFRICA",
    gdp: 900,
    literacy: 68,
    phones: 9.3,
    climate: 1.5,
    birthrate: 40.43,
    deathrate: 16.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "N. Mariana Islands",
    region: "OCEANIA",
    gdp: 12500,
    literacy: 97,
    phones: 254.7,
    climate: 2,
    birthrate: 19.43,
    deathrate: 2.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Norway",
    region: "WESTERN EUROPE",
    gdp: 37800,
    literacy: 100,
    phones: 461.7,
    climate: 3,
    birthrate: 11.46,
    deathrate: 9.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Oman",
    region: "NEAR EAST",
    gdp: 13100,
    literacy: 75.8,
    phones: 85.5,
    climate: 1,
    birthrate: 36.24,
    deathrate: 3.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Pakistan",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 2100,
    literacy: 45.7,
    phones: 31.8,
    climate: 1,
    birthrate: 29.74,
    deathrate: 8.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Palau",
    region: "OCEANIA",
    gdp: 9000,
    literacy: 92,
    phones: 325.6,
    climate: 2,
    birthrate: 18.03,
    deathrate: 6.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Panama",
    region: "LATIN AMER. & CARIB",
    gdp: 6300,
    literacy: 92.6,
    phones: 137.9,
    climate: 2,
    birthrate: 21.74,
    deathrate: 5.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Papua New Guinea",
    region: "OCEANIA",
    gdp: 2200,
    literacy: 64.6,
    phones: 10.9,
    climate: 2,
    birthrate: 29.36,
    deathrate: 7.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Paraguay",
    region: "LATIN AMER. & CARIB",
    gdp: 4700,
    literacy: 94,
    phones: 49.2,
    climate: 2,
    birthrate: 29.1,
    deathrate: 4.49,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Peru",
    region: "LATIN AMER. & CARIB",
    gdp: 5100,
    literacy: 90.9,
    phones: 79.5,
    climate: 1.5,
    birthrate: 20.48,
    deathrate: 6.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Philippines",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 4600,
    literacy: 92.6,
    phones: 38.4,
    climate: 2,
    birthrate: 24.89,
    deathrate: 5.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Poland",
    region: "EASTERN EUROPE",
    gdp: 11100,
    literacy: 99.8,
    phones: 306.3,
    climate: 3,
    birthrate: 9.85,
    deathrate: 9.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Portugal",
    region: "WESTERN EUROPE",
    gdp: 18000,
    literacy: 93.3,
    phones: 399.2,
    climate: 3,
    birthrate: 10.72,
    deathrate: 10.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Puerto Rico",
    region: "LATIN AMER. & CARIB",
    gdp: 16800,
    literacy: 94.1,
    phones: 283.1,
    climate: 2,
    birthrate: 12.77,
    deathrate: 7.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Qatar",
    region: "NEAR EAST",
    gdp: 21500,
    literacy: 82.5,
    phones: 232,
    climate: 1,
    birthrate: 15.56,
    deathrate: 4.72,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Reunion",
    region: "SUB-SAHARAN AFRICA",
    gdp: 5800,
    literacy: 88.9,
    phones: 380.9,
    climate: 2,
    birthrate: 18.9,
    deathrate: 5.49,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Romania",
    region: "EASTERN EUROPE",
    gdp: 7000,
    literacy: 98.4,
    phones: 196.9,
    climate: 3,
    birthrate: 10.7,
    deathrate: 11.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Russia",
    region: "C.W. OF IND. STATES",
    gdp: 8900,
    literacy: 99.6,
    phones: 280.6,
    climate: 0,
    birthrate: 9.95,
    deathrate: 14.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Rwanda",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1300,
    literacy: 70.4,
    phones: 2.7,
    climate: 3,
    birthrate: 40.37,
    deathrate: 16.09,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saint Helena",
    region: "SUB-SAHARAN AFRICA",
    gdp: 2500,
    literacy: 97,
    phones: 293.3,
    climate: 0,
    birthrate: 12.13,
    deathrate: 6.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saint Kitts & Nevis",
    region: "LATIN AMER. & CARIB",
    gdp: 8800,
    literacy: 97,
    phones: 638.9,
    climate: 2,
    birthrate: 18.02,
    deathrate: 8.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saint Lucia",
    region: "LATIN AMER. & CARIB",
    gdp: 5400,
    literacy: 67,
    phones: 303.3,
    climate: 2,
    birthrate: 19.68,
    deathrate: 5.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "St Pierre & Miquelon",
    region: "NORTHERN AMERICA",
    gdp: 6900,
    literacy: 99,
    phones: 683.2,
    climate: 0,
    birthrate: 13.52,
    deathrate: 6.83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saint Vincent and the Grenadines",
    region: "LATIN AMER. & CARIB",
    gdp: 2900,
    literacy: 96,
    phones: 190.9,
    climate: 2,
    birthrate: 16.18,
    deathrate: 5.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Samoa",
    region: "OCEANIA",
    gdp: 5600,
    literacy: 99.7,
    phones: 75.2,
    climate: 2,
    birthrate: 16.43,
    deathrate: 6.62,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "San Marino",
    region: "WESTERN EUROPE",
    gdp: 34600,
    literacy: 96,
    phones: 704.3,
    climate: 0,
    birthrate: 10.02,
    deathrate: 8.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sao Tome & Principe",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1200,
    literacy: 79.3,
    phones: 36.2,
    climate: 2,
    birthrate: 40.25,
    deathrate: 6.47,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saudi Arabia",
    region: "NEAR EAST",
    gdp: 11800,
    literacy: 78.8,
    phones: 140.6,
    climate: 1,
    birthrate: 29.34,
    deathrate: 2.58,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Senegal",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1600,
    literacy: 40.2,
    phones: 22.2,
    climate: 2,
    birthrate: 32.78,
    deathrate: 9.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Serbia",
    region: "EASTERN EUROPE",
    gdp: 2200,
    literacy: 93,
    phones: 285.8,
    climate: 0,
    birthrate: 0,
    deathrate: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Seychelles",
    region: "SUB-SAHARAN AFRICA",
    gdp: 7800,
    literacy: 58,
    phones: 262.4,
    climate: 2,
    birthrate: 16.03,
    deathrate: 6.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sierra Leone",
    region: "SUB-SAHARAN AFRICA",
    gdp: 500,
    literacy: 31.4,
    phones: 4,
    climate: 2,
    birthrate: 45.76,
    deathrate: 23.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Singapore",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 23700,
    literacy: 92.5,
    phones: 411.4,
    climate: 2,
    birthrate: 9.34,
    deathrate: 4.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovakia",
    region: "EASTERN EUROPE",
    gdp: 13300,
    literacy: 0,
    phones: 220.1,
    climate: 3,
    birthrate: 10.65,
    deathrate: 9.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovenia",
    region: "EASTERN EUROPE",
    gdp: 19000,
    literacy: 99.7,
    phones: 406.1,
    climate: 0,
    birthrate: 8.98,
    deathrate: 10.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Solomon Islands",
    region: "OCEANIA",
    gdp: 1700,
    literacy: 0,
    phones: 13.4,
    climate: 2,
    birthrate: 30.01,
    deathrate: 3.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Somalia",
    region: "SUB-SAHARAN AFRICA",
    gdp: 500,
    literacy: 37.8,
    phones: 11.3,
    climate: 1,
    birthrate: 45.13,
    deathrate: 16.63,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "South Africa",
    region: "SUB-SAHARAN AFRICA",
    gdp: 10700,
    literacy: 86.4,
    phones: 107,
    climate: 1,
    birthrate: 18.2,
    deathrate: 22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Spain",
    region: "WESTERN EUROPE",
    gdp: 22000,
    literacy: 97.9,
    phones: 453.5,
    climate: 3,
    birthrate: 10.06,
    deathrate: 9.72,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sri Lanka",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 3700,
    literacy: 92.3,
    phones: 61.5,
    climate: 2,
    birthrate: 15.51,
    deathrate: 6.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sudan",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1900,
    literacy: 61.1,
    phones: 16.3,
    climate: 2,
    birthrate: 34.53,
    deathrate: 8.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Suriname",
    region: "LATIN AMER. & CARIB",
    gdp: 4000,
    literacy: 93,
    phones: 184.7,
    climate: 2,
    birthrate: 18.02,
    deathrate: 7.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Swaziland",
    region: "SUB-SAHARAN AFRICA",
    gdp: 4900,
    literacy: 81.6,
    phones: 30.8,
    climate: 2.5,
    birthrate: 27.41,
    deathrate: 29.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sweden",
    region: "WESTERN EUROPE",
    gdp: 26800,
    literacy: 99,
    phones: 715,
    climate: 3,
    birthrate: 10.27,
    deathrate: 10.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Switzerland",
    region: "WESTERN EUROPE",
    gdp: 32700,
    literacy: 99,
    phones: 680.9,
    climate: 3,
    birthrate: 9.71,
    deathrate: 8.49,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Syria",
    region: "NEAR EAST",
    gdp: 3300,
    literacy: 76.9,
    phones: 153.8,
    climate: 1,
    birthrate: 27.76,
    deathrate: 4.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Taiwan",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 23400,
    literacy: 96.1,
    phones: 591,
    climate: 2,
    birthrate: 12.56,
    deathrate: 6.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tajikistan",
    region: "C.W. OF IND. STATES",
    gdp: 1000,
    literacy: 99.4,
    phones: 33.5,
    climate: 2,
    birthrate: 32.65,
    deathrate: 8.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tanzania",
    region: "SUB-SAHARAN AFRICA",
    gdp: 600,
    literacy: 78.2,
    phones: 4,
    climate: 0,
    birthrate: 37.71,
    deathrate: 16.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Thailand",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 7400,
    literacy: 92.6,
    phones: 108.9,
    climate: 2,
    birthrate: 13.87,
    deathrate: 7.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Togo",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1500,
    literacy: 60.9,
    phones: 10.6,
    climate: 2,
    birthrate: 37.01,
    deathrate: 9.83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tonga",
    region: "OCEANIA",
    gdp: 2200,
    literacy: 98.5,
    phones: 97.7,
    climate: 2,
    birthrate: 25.37,
    deathrate: 5.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Trinidad & Tobago",
    region: "LATIN AMER. & CARIB",
    gdp: 9500,
    literacy: 98.6,
    phones: 303.5,
    climate: 2,
    birthrate: 12.9,
    deathrate: 10.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tunisia",
    region: "NORTHERN AFRICA",
    gdp: 6900,
    literacy: 74.2,
    phones: 123.6,
    climate: 3,
    birthrate: 15.52,
    deathrate: 5.13,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Turkey",
    region: "NEAR EAST",
    gdp: 6700,
    literacy: 86.5,
    phones: 269.5,
    climate: 3,
    birthrate: 16.62,
    deathrate: 5.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Turkmenistan",
    region: "C.W. OF IND. STATES",
    gdp: 5800,
    literacy: 98,
    phones: 74.6,
    climate: 1,
    birthrate: 27.61,
    deathrate: 8.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Turks & Caicos Is",
    region: "LATIN AMER. & CARIB",
    gdp: 9600,
    literacy: 98,
    phones: 269.5,
    climate: 2,
    birthrate: 21.84,
    deathrate: 4.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tuvalu",
    region: "OCEANIA",
    gdp: 1100,
    literacy: 0,
    phones: 59.3,
    climate: 2,
    birthrate: 22.18,
    deathrate: 7.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uganda",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1400,
    literacy: 69.9,
    phones: 3.6,
    climate: 2,
    birthrate: 47.35,
    deathrate: 12.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ukraine",
    region: "C.W. OF IND. STATES",
    gdp: 5400,
    literacy: 99.7,
    phones: 259.9,
    climate: 3,
    birthrate: 8.82,
    deathrate: 14.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Arab Emirates",
    region: "NEAR EAST",
    gdp: 23200,
    literacy: 77.9,
    phones: 475.3,
    climate: 1,
    birthrate: 18.96,
    deathrate: 4.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Kingdom",
    region: "WESTERN EUROPE",
    gdp: 27700,
    literacy: 99,
    phones: 543.5,
    climate: 3,
    birthrate: 10.71,
    deathrate: 10.13,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United States",
    region: "NORTHERN AMERICA",
    gdp: 37800,
    literacy: 97,
    phones: 898,
    climate: 3,
    birthrate: 14.14,
    deathrate: 8.26,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uruguay",
    region: "LATIN AMER. & CARIB",
    gdp: 12800,
    literacy: 98,
    phones: 291.4,
    climate: 3,
    birthrate: 13.91,
    deathrate: 9.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uzbekistan",
    region: "C.W. OF IND. STATES",
    gdp: 1700,
    literacy: 99.3,
    phones: 62.9,
    climate: 1,
    birthrate: 26.36,
    deathrate: 7.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Vanuatu",
    region: "OCEANIA",
    gdp: 2900,
    literacy: 53,
    phones: 32.6,
    climate: 2,
    birthrate: 22.72,
    deathrate: 7.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Venezuela",
    region: "LATIN AMER. & CARIB",
    gdp: 4800,
    literacy: 93.4,
    phones: 140.1,
    climate: 2,
    birthrate: 18.71,
    deathrate: 4.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Vietnam",
    region: "ASIA (EX. NEAR EAST)",
    gdp: 2500,
    literacy: 90.3,
    phones: 187.7,
    climate: 2,
    birthrate: 16.86,
    deathrate: 6.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Virgin Islands",
    region: "LATIN AMER. & CARIB",
    gdp: 17200,
    literacy: 0,
    phones: 652.8,
    climate: 2,
    birthrate: 13.96,
    deathrate: 6.43,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Wallis and Futuna",
    region: "OCEANIA",
    gdp: 3700,
    literacy: 50,
    phones: 118.6,
    climate: 2,
    birthrate: 0,
    deathrate: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "West Bank",
    region: "NEAR EAST",
    gdp: 800,
    literacy: 0,
    phones: 145.2,
    climate: 3,
    birthrate: 31.67,
    deathrate: 3.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Western Sahara",
    region: "NORTHERN AFRICA",
    gdp: null,
    literacy: 0,
    phones: 0,
    climate: 1,
    birthrate: 0,
    deathrate: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Yemen",
    region: "NEAR EAST",
    gdp: 800,
    literacy: 50.2,
    phones: 37.2,
    climate: 1,
    birthrate: 42.89,
    deathrate: 8.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Zambia",
    region: "SUB-SAHARAN AFRICA",
    gdp: 800,
    literacy: 80.6,
    phones: 8.2,
    climate: 2,
    birthrate: 41,
    deathrate: 19.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Zimbabwe",
    region: "SUB-SAHARAN AFRICA",
    gdp: 1900,
    literacy: 90.7,
    phones: 26.8,
    climate: 2,
    birthrate: 28.01,
    deathrate: 21.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
].map((data, i) => {
  data.id = i + 1;
  return data;
});
