module.exports = [
  {
    country: "Venezuela",
    price_to_income: 133.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Syria",
    price_to_income: 60.83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hong Kong",
    price_to_income: 47.46,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cambodia",
    price_to_income: 42.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kenya",
    price_to_income: 31.63,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sri Lanka",
    price_to_income: 31.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "China",
    price_to_income: 29.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iran",
    price_to_income: 25.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nepal",
    price_to_income: 24.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Philippines",
    price_to_income: 24.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Argentina",
    price_to_income: 24.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Taiwan",
    price_to_income: 23.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Singapore",
    price_to_income: 22.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Thailand",
    price_to_income: 22.26,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Vietnam",
    price_to_income: 21.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Colombia",
    price_to_income: 19.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Serbia",
    price_to_income: 18.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Indonesia",
    price_to_income: 18.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Algeria",
    price_to_income: 17.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "South Korea",
    price_to_income: 17.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Armenia",
    price_to_income: 16.62,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Brazil",
    price_to_income: 16.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uruguay",
    price_to_income: 16.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Azerbaijan",
    price_to_income: 16.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Albania",
    price_to_income: 15.49,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Czech Republic",
    price_to_income: 15.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uzbekistan",
    price_to_income: 15.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Peru",
    price_to_income: 14.95,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Chile",
    price_to_income: 14.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hungary",
    price_to_income: 14.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belarus",
    price_to_income: 14.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Georgia",
    price_to_income: 14.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Morocco",
    price_to_income: 14.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Croatia",
    price_to_income: 13.73,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Dominican Republic",
    price_to_income: 13.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Montenegro",
    price_to_income: 13.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lebanon",
    price_to_income: 13.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bangladesh",
    price_to_income: 13.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "France",
    price_to_income: 13.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Egypt",
    price_to_income: 13.01,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Japan",
    price_to_income: 13,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Israel",
    price_to_income: 12.83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ecuador",
    price_to_income: 12.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Portugal",
    price_to_income: 12.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Panama",
    price_to_income: 12.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "North Macedonia",
    price_to_income: 12.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bosnia And Herzegovina",
    price_to_income: 12.58,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malta",
    price_to_income: 12.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kuwait",
    price_to_income: 12.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ukraine",
    price_to_income: 12.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Pakistan",
    price_to_income: 11.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Luxembourg",
    price_to_income: 11.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Poland",
    price_to_income: 11.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "India",
    price_to_income: 11.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Romania",
    price_to_income: 11.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lithuania",
    price_to_income: 10.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Austria",
    price_to_income: 10.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kazakhstan",
    price_to_income: 10.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Russia",
    price_to_income: 10.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Honduras",
    price_to_income: 10.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kosovo (Disputed Territory)",
    price_to_income: 10.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mexico",
    price_to_income: 10.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Tunisia",
    price_to_income: 10.63,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Greece",
    price_to_income: 10.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovenia",
    price_to_income: 10.49,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Costa Rica",
    price_to_income: 10.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovakia",
    price_to_income: 10.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Kingdom",
    price_to_income: 10.09,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Guatemala",
    price_to_income: 10.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malaysia",
    price_to_income: 9.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Italy",
    price_to_income: 9.71,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bolivia",
    price_to_income: 9.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Germany",
    price_to_income: 9.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Spain",
    price_to_income: 9.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sweden",
    price_to_income: 9.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iraq",
    price_to_income: 9.12,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Oman",
    price_to_income: 9.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Estonia",
    price_to_income: 9.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Latvia",
    price_to_income: 8.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Norway",
    price_to_income: 8.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Switzerland",
    price_to_income: 8.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bahrain",
    price_to_income: 8.63,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "New Zealand",
    price_to_income: 8.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bulgaria",
    price_to_income: 8.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Jordan",
    price_to_income: 8.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Finland",
    price_to_income: 8.35,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cyprus",
    price_to_income: 8.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Canada",
    price_to_income: 7.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Turkey",
    price_to_income: 7.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Australia",
    price_to_income: 7.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Netherlands",
    price_to_income: 7.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ireland",
    price_to_income: 7.49,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Denmark",
    price_to_income: 7.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belgium",
    price_to_income: 6.91,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iceland",
    price_to_income: 6.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Trinidad And Tobago",
    price_to_income: 6.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Qatar",
    price_to_income: 5.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Arab Emirates",
    price_to_income: 5.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Namibia",
    price_to_income: 5.15,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Palestine",
    price_to_income: 4.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "South Africa",
    price_to_income: 3.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Puerto Rico",
    price_to_income: 3.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United States",
    price_to_income: 3.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saudi Arabia",
    price_to_income: 2.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
].map((data, i) => {
  data.id = i + 1;
  return data;
});
