module.exports = [
  {
    country: "Denmark",
    quality_of_life_index: 192.67,
    purchasing_power_index: 100.88,
    health_care_index: 80,
    cost_of_living_index: 83,
    property_price_to_income_ratio: 7.45,
    pollution_index: 21.33,
    climate_index: 81.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Switzerland",
    quality_of_life_index: 192.01,
    purchasing_power_index: 119.53,
    health_care_index: 72.44,
    cost_of_living_index: 122.4,
    property_price_to_income_ratio: 8.68,
    pollution_index: 22.39,
    climate_index: 79.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Finland",
    quality_of_life_index: 190.22,
    purchasing_power_index: 99.93,
    health_care_index: 75.79,
    cost_of_living_index: 70.29,
    property_price_to_income_ratio: 8.35,
    pollution_index: 11.55,
    climate_index: 58.87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Australia",
    quality_of_life_index: 186.21,
    purchasing_power_index: 107.31,
    health_care_index: 77.38,
    cost_of_living_index: 73.54,
    property_price_to_income_ratio: 7.52,
    pollution_index: 23.46,
    climate_index: 92.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Netherlands",
    quality_of_life_index: 183.67,
    purchasing_power_index: 90.73,
    health_care_index: 74.65,
    cost_of_living_index: 73.75,
    property_price_to_income_ratio: 7.51,
    pollution_index: 27.41,
    climate_index: 87.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Austria",
    quality_of_life_index: 182.5,
    purchasing_power_index: 82.38,
    health_care_index: 78.73,
    cost_of_living_index: 70.38,
    property_price_to_income_ratio: 10.88,
    pollution_index: 22.19,
    climate_index: 77.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iceland",
    quality_of_life_index: 181.75,
    purchasing_power_index: 79.44,
    health_care_index: 65.92,
    cost_of_living_index: 100.48,
    property_price_to_income_ratio: 6.74,
    pollution_index: 16.21,
    climate_index: 68.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "New Zealand",
    quality_of_life_index: 181.02,
    purchasing_power_index: 92.66,
    health_care_index: 73.81,
    cost_of_living_index: 72.53,
    property_price_to_income_ratio: 8.52,
    pollution_index: 23.4,
    climate_index: 95.46,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Germany",
    quality_of_life_index: 179.78,
    purchasing_power_index: 102.36,
    health_care_index: 73.32,
    cost_of_living_index: 65.26,
    property_price_to_income_ratio: 9.38,
    pollution_index: 29.03,
    climate_index: 83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Estonia",
    quality_of_life_index: 177.82,
    purchasing_power_index: 71.3,
    health_care_index: 72.67,
    cost_of_living_index: 50.93,
    property_price_to_income_ratio: 9.06,
    pollution_index: 19.81,
    climate_index: 64.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sweden",
    quality_of_life_index: 175.95,
    purchasing_power_index: 101.73,
    health_care_index: 69.23,
    cost_of_living_index: 69.85,
    property_price_to_income_ratio: 9.27,
    pollution_index: 18.09,
    climate_index: 73.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Norway",
    quality_of_life_index: 175.19,
    purchasing_power_index: 88.38,
    health_care_index: 74.36,
    cost_of_living_index: 101.43,
    property_price_to_income_ratio: 8.77,
    pollution_index: 20.35,
    climate_index: 71.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovenia",
    quality_of_life_index: 172.15,
    purchasing_power_index: 66.31,
    health_care_index: 64.58,
    cost_of_living_index: 53.43,
    property_price_to_income_ratio: 10.49,
    pollution_index: 24.06,
    climate_index: 77.56,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United States",
    quality_of_life_index: 172.11,
    purchasing_power_index: 109.52,
    health_care_index: 69.27,
    cost_of_living_index: 71.05,
    property_price_to_income_ratio: 3.52,
    pollution_index: 36.88,
    climate_index: 77.54,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Spain",
    quality_of_life_index: 169.82,
    purchasing_power_index: 72.03,
    health_care_index: 78.88,
    cost_of_living_index: 53.77,
    property_price_to_income_ratio: 9.37,
    pollution_index: 39.99,
    climate_index: 94.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Japan",
    quality_of_life_index: 167.99,
    purchasing_power_index: 87.28,
    health_care_index: 81.14,
    cost_of_living_index: 83.35,
    property_price_to_income_ratio: 13,
    pollution_index: 39.59,
    climate_index: 84.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Oman",
    quality_of_life_index: 167.09,
    purchasing_power_index: 80.97,
    health_care_index: 58.15,
    cost_of_living_index: 49.28,
    property_price_to_income_ratio: 9.08,
    pollution_index: 37.74,
    climate_index: 67.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Canada",
    quality_of_life_index: 163.47,
    purchasing_power_index: 95.09,
    health_care_index: 71.58,
    cost_of_living_index: 67.62,
    property_price_to_income_ratio: 7.97,
    pollution_index: 27.83,
    climate_index: 50.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Portugal",
    quality_of_life_index: 162.91,
    purchasing_power_index: 49.43,
    health_care_index: 71.88,
    cost_of_living_index: 49.52,
    property_price_to_income_ratio: 12.7,
    pollution_index: 30.89,
    climate_index: 97.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Kingdom",
    quality_of_life_index: 162.71,
    purchasing_power_index: 91.73,
    health_care_index: 74.46,
    cost_of_living_index: 67.28,
    property_price_to_income_ratio: 10.09,
    pollution_index: 40.56,
    climate_index: 87.62,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Qatar",
    quality_of_life_index: 162.29,
    purchasing_power_index: 111.69,
    health_care_index: 73.3,
    cost_of_living_index: 64.04,
    property_price_to_income_ratio: 5.82,
    pollution_index: 61.06,
    climate_index: 36.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lithuania",
    quality_of_life_index: 159.42,
    purchasing_power_index: 57.85,
    health_care_index: 69.49,
    cost_of_living_index: 44.28,
    property_price_to_income_ratio: 10.9,
    pollution_index: 28.8,
    climate_index: 67.76,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Croatia",
    quality_of_life_index: 159.01,
    purchasing_power_index: 50.42,
    health_care_index: 62.68,
    cost_of_living_index: 49.7,
    property_price_to_income_ratio: 13.73,
    pollution_index: 30.46,
    climate_index: 89.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "United Arab Emirates",
    quality_of_life_index: 156.67,
    purchasing_power_index: 91.58,
    health_care_index: 67.04,
    cost_of_living_index: 61.98,
    property_price_to_income_ratio: 5.29,
    pollution_index: 51.15,
    climate_index: 45.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Czech Republic",
    quality_of_life_index: 156.24,
    purchasing_power_index: 62.82,
    health_care_index: 74.62,
    cost_of_living_index: 46.15,
    property_price_to_income_ratio: 15.42,
    pollution_index: 40.23,
    climate_index: 77.13,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "France",
    quality_of_life_index: 153.95,
    purchasing_power_index: 80.36,
    health_care_index: 79.99,
    cost_of_living_index: 74.14,
    property_price_to_income_ratio: 13.04,
    pollution_index: 43.56,
    climate_index: 90.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ireland",
    quality_of_life_index: 153.53,
    purchasing_power_index: 80.88,
    health_care_index: 51.89,
    cost_of_living_index: 75.91,
    property_price_to_income_ratio: 7.49,
    pollution_index: 33.99,
    climate_index: 89.13,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belgium",
    quality_of_life_index: 153.47,
    purchasing_power_index: 86.28,
    health_care_index: 74.34,
    cost_of_living_index: 71.78,
    property_price_to_income_ratio: 6.91,
    pollution_index: 52.94,
    climate_index: 85.99,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Slovakia",
    quality_of_life_index: 152.53,
    purchasing_power_index: 56.94,
    health_care_index: 60.02,
    cost_of_living_index: 44.46,
    property_price_to_income_ratio: 10.25,
    pollution_index: 39.66,
    climate_index: 78.13,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Saudi Arabia",
    quality_of_life_index: 150.56,
    purchasing_power_index: 100,
    health_care_index: 59.11,
    cost_of_living_index: 48.34,
    property_price_to_income_ratio: 2.79,
    pollution_index: 65.09,
    climate_index: 45.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Latvia",
    quality_of_life_index: 150,
    purchasing_power_index: 52.48,
    health_care_index: 62.91,
    cost_of_living_index: 47.94,
    property_price_to_income_ratio: 8.85,
    pollution_index: 33.73,
    climate_index: 74.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Israel",
    quality_of_life_index: 149.94,
    purchasing_power_index: 78.09,
    health_care_index: 73.29,
    cost_of_living_index: 81.15,
    property_price_to_income_ratio: 12.83,
    pollution_index: 57.25,
    climate_index: 93.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Cyprus",
    quality_of_life_index: 147.93,
    purchasing_power_index: 57.41,
    health_care_index: 51.75,
    cost_of_living_index: 57.93,
    property_price_to_income_ratio: 8.2,
    pollution_index: 53.55,
    climate_index: 92.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Singapore",
    quality_of_life_index: 144.39,
    purchasing_power_index: 88.96,
    health_care_index: 70.84,
    cost_of_living_index: 81.1,
    property_price_to_income_ratio: 22.31,
    pollution_index: 33.48,
    climate_index: 57.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Taiwan",
    quality_of_life_index: 143.23,
    purchasing_power_index: 65.67,
    health_care_index: 86.71,
    cost_of_living_index: 61.37,
    property_price_to_income_ratio: 23.69,
    pollution_index: 63.35,
    climate_index: 84.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Poland",
    quality_of_life_index: 141.83,
    purchasing_power_index: 59.61,
    health_care_index: 61.01,
    cost_of_living_index: 40.04,
    property_price_to_income_ratio: 11.38,
    pollution_index: 54.46,
    climate_index: 76.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Italy",
    quality_of_life_index: 140.76,
    purchasing_power_index: 65.59,
    health_care_index: 66.59,
    cost_of_living_index: 67.26,
    property_price_to_income_ratio: 9.71,
    pollution_index: 55.63,
    climate_index: 92.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "South Korea",
    quality_of_life_index: 139.02,
    purchasing_power_index: 85.21,
    health_care_index: 81.97,
    cost_of_living_index: 78.18,
    property_price_to_income_ratio: 17.37,
    pollution_index: 62.48,
    climate_index: 68.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Belarus",
    quality_of_life_index: 134.83,
    purchasing_power_index: 37,
    health_care_index: 59.04,
    cost_of_living_index: 34.7,
    property_price_to_income_ratio: 14.65,
    pollution_index: 43.63,
    climate_index: 64.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Greece",
    quality_of_life_index: 133.07,
    purchasing_power_index: 43.68,
    health_care_index: 56.21,
    cost_of_living_index: 55.67,
    property_price_to_income_ratio: 10.6,
    pollution_index: 52.55,
    climate_index: 94.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Romania",
    quality_of_life_index: 132.44,
    purchasing_power_index: 48.86,
    health_care_index: 55.06,
    cost_of_living_index: 35.31,
    property_price_to_income_ratio: 11.33,
    pollution_index: 58.42,
    climate_index: 77.62,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "South Africa",
    quality_of_life_index: 131.97,
    purchasing_power_index: 73.61,
    health_care_index: 64.14,
    cost_of_living_index: 42.87,
    property_price_to_income_ratio: 3.93,
    pollution_index: 57.3,
    climate_index: 95.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bulgaria",
    quality_of_life_index: 129.8,
    purchasing_power_index: 49.37,
    health_care_index: 55.4,
    cost_of_living_index: 36.7,
    property_price_to_income_ratio: 8.52,
    pollution_index: 65.33,
    climate_index: 82.76,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hungary",
    quality_of_life_index: 128.16,
    purchasing_power_index: 47.55,
    health_care_index: 47.8,
    cost_of_living_index: 40.85,
    property_price_to_income_ratio: 14.77,
    pollution_index: 48.29,
    climate_index: 79.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Turkey",
    quality_of_life_index: 127.1,
    purchasing_power_index: 40.85,
    health_care_index: 69.8,
    cost_of_living_index: 34.69,
    property_price_to_income_ratio: 7.81,
    pollution_index: 67.35,
    climate_index: 93.26,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Uruguay",
    quality_of_life_index: 125.98,
    purchasing_power_index: 37.46,
    health_care_index: 66.28,
    cost_of_living_index: 51.04,
    property_price_to_income_ratio: 16.34,
    pollution_index: 44.84,
    climate_index: 98.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ecuador",
    quality_of_life_index: 125.14,
    purchasing_power_index: 36.08,
    health_care_index: 70.59,
    cost_of_living_index: 40.98,
    property_price_to_income_ratio: 12.7,
    pollution_index: 57,
    climate_index: 94.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bosnia And Herzegovina",
    quality_of_life_index: 121.89,
    purchasing_power_index: 41.83,
    health_care_index: 52.26,
    cost_of_living_index: 35.97,
    property_price_to_income_ratio: 12.58,
    pollution_index: 62.33,
    climate_index: 80.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Chile",
    quality_of_life_index: 119.76,
    purchasing_power_index: 42.5,
    health_care_index: 65.44,
    cost_of_living_index: 43.62,
    property_price_to_income_ratio: 14.93,
    pollution_index: 65.78,
    climate_index: 90.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Mexico",
    quality_of_life_index: 118.55,
    purchasing_power_index: 41.81,
    health_care_index: 70.12,
    cost_of_living_index: 35.72,
    property_price_to_income_ratio: 10.67,
    pollution_index: 66.1,
    climate_index: 86.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Malaysia",
    quality_of_life_index: 118.44,
    purchasing_power_index: 64.49,
    health_care_index: 68.1,
    cost_of_living_index: 39.12,
    property_price_to_income_ratio: 9.94,
    pollution_index: 63.18,
    climate_index: 57.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Serbia",
    quality_of_life_index: 116.3,
    purchasing_power_index: 36.72,
    health_care_index: 51.27,
    cost_of_living_index: 35.72,
    property_price_to_income_ratio: 18.94,
    pollution_index: 60.32,
    climate_index: 83.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Georgia",
    quality_of_life_index: 115.95,
    purchasing_power_index: 24.88,
    health_care_index: 51.24,
    cost_of_living_index: 28.48,
    property_price_to_income_ratio: 14.21,
    pollution_index: 71.09,
    climate_index: 84.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kuwait",
    quality_of_life_index: 115.75,
    purchasing_power_index: 85.59,
    health_care_index: 56.21,
    cost_of_living_index: 50.37,
    property_price_to_income_ratio: 12.28,
    pollution_index: 68.69,
    climate_index: 20.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Argentina",
    quality_of_life_index: 115.31,
    purchasing_power_index: 47.22,
    health_care_index: 69.25,
    cost_of_living_index: 32.95,
    property_price_to_income_ratio: 24.53,
    pollution_index: 50.67,
    climate_index: 98.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Jordan",
    quality_of_life_index: 112.4,
    purchasing_power_index: 34.88,
    health_care_index: 64.6,
    cost_of_living_index: 53.67,
    property_price_to_income_ratio: 8.42,
    pollution_index: 77.78,
    climate_index: 89.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "North Macedonia",
    quality_of_life_index: 110.46,
    purchasing_power_index: 37.15,
    health_care_index: 56.38,
    cost_of_living_index: 31.59,
    property_price_to_income_ratio: 12.6,
    pollution_index: 80.23,
    climate_index: 76.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "India",
    quality_of_life_index: 108.63,
    purchasing_power_index: 54.3,
    health_care_index: 67.13,
    cost_of_living_index: 24.58,
    property_price_to_income_ratio: 11.38,
    pollution_index: 78.87,
    climate_index: 64.87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Panama",
    quality_of_life_index: 108.36,
    purchasing_power_index: 34.23,
    health_care_index: 59.93,
    cost_of_living_index: 54.16,
    property_price_to_income_ratio: 12.6,
    pollution_index: 63.09,
    climate_index: 67.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Lebanon",
    quality_of_life_index: 106.56,
    purchasing_power_index: 44.47,
    health_care_index: 64.38,
    cost_of_living_index: 60.5,
    property_price_to_income_ratio: 13.23,
    pollution_index: 88.37,
    climate_index: 94.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Colombia",
    quality_of_life_index: 105.83,
    purchasing_power_index: 31.12,
    health_care_index: 67.24,
    cost_of_living_index: 30.66,
    property_price_to_income_ratio: 19.65,
    pollution_index: 62.83,
    climate_index: 96.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Brazil",
    quality_of_life_index: 105.65,
    purchasing_power_index: 32.81,
    health_care_index: 56.29,
    cost_of_living_index: 40.22,
    property_price_to_income_ratio: 16.41,
    pollution_index: 54.98,
    climate_index: 97.16,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Morocco",
    quality_of_life_index: 105.46,
    purchasing_power_index: 35.25,
    health_care_index: 45.72,
    cost_of_living_index: 34.32,
    property_price_to_income_ratio: 14.18,
    pollution_index: 70.64,
    climate_index: 91.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Pakistan",
    quality_of_life_index: 105.44,
    purchasing_power_index: 30.57,
    health_care_index: 60.59,
    cost_of_living_index: 21.98,
    property_price_to_income_ratio: 11.98,
    pollution_index: 74.25,
    climate_index: 71.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Ukraine",
    quality_of_life_index: 104.77,
    purchasing_power_index: 31.8,
    health_care_index: 52.33,
    cost_of_living_index: 33.18,
    property_price_to_income_ratio: 12.23,
    pollution_index: 65.08,
    climate_index: 71.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "China",
    quality_of_life_index: 102.81,
    purchasing_power_index: 60.88,
    health_care_index: 64.48,
    cost_of_living_index: 40.04,
    property_price_to_income_ratio: 29.06,
    pollution_index: 80.77,
    climate_index: 79.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Russia",
    quality_of_life_index: 102.31,
    purchasing_power_index: 38.94,
    health_care_index: 57.59,
    cost_of_living_index: 39.21,
    property_price_to_income_ratio: 10.77,
    pollution_index: 62.79,
    climate_index: 40.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Thailand",
    quality_of_life_index: 101.88,
    purchasing_power_index: 35.45,
    health_care_index: 77.95,
    cost_of_living_index: 49.77,
    property_price_to_income_ratio: 22.26,
    pollution_index: 75.07,
    climate_index: 69.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Hong Kong",
    quality_of_life_index: 99.05,
    purchasing_power_index: 65.32,
    health_care_index: 66.08,
    cost_of_living_index: 77.22,
    property_price_to_income_ratio: 47.46,
    pollution_index: 67.69,
    climate_index: 83.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Indonesia",
    quality_of_life_index: 97.47,
    purchasing_power_index: 25.05,
    health_care_index: 60.48,
    cost_of_living_index: 37.27,
    property_price_to_income_ratio: 18.88,
    pollution_index: 66.56,
    climate_index: 74.15,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kazakhstan",
    quality_of_life_index: 88.31,
    purchasing_power_index: 38.36,
    health_care_index: 50.7,
    cost_of_living_index: 30.64,
    property_price_to_income_ratio: 10.86,
    pollution_index: 75.15,
    climate_index: 39.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Vietnam",
    quality_of_life_index: 87.48,
    purchasing_power_index: 28.14,
    health_care_index: 57.7,
    cost_of_living_index: 38.34,
    property_price_to_income_ratio: 21.36,
    pollution_index: 86.47,
    climate_index: 71.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Egypt",
    quality_of_life_index: 86.54,
    purchasing_power_index: 22.41,
    health_care_index: 45.84,
    cost_of_living_index: 29.54,
    property_price_to_income_ratio: 13.01,
    pollution_index: 85.65,
    climate_index: 91.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Peru",
    quality_of_life_index: 85.46,
    purchasing_power_index: 33.95,
    health_care_index: 56.15,
    cost_of_living_index: 38.65,
    property_price_to_income_ratio: 14.95,
    pollution_index: 84.13,
    climate_index: 97.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Philippines",
    quality_of_life_index: 85.37,
    purchasing_power_index: 23.48,
    health_care_index: 67.47,
    cost_of_living_index: 37.63,
    property_price_to_income_ratio: 24.6,
    pollution_index: 74.28,
    climate_index: 60.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Sri Lanka",
    quality_of_life_index: 85.16,
    purchasing_power_index: 24.45,
    health_care_index: 72.53,
    cost_of_living_index: 31.61,
    property_price_to_income_ratio: 31.14,
    pollution_index: 59.14,
    climate_index: 59.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Iran",
    quality_of_life_index: 74.14,
    purchasing_power_index: 22.69,
    health_care_index: 51.7,
    cost_of_living_index: 39.01,
    property_price_to_income_ratio: 25.11,
    pollution_index: 77.45,
    climate_index: 70.99,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Kenya",
    quality_of_life_index: 70.56,
    purchasing_power_index: 27.32,
    health_care_index: 55.59,
    cost_of_living_index: 40.21,
    property_price_to_income_ratio: 31.63,
    pollution_index: 76.6,
    climate_index: 99.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Bangladesh",
    quality_of_life_index: 70.03,
    purchasing_power_index: 33.21,
    health_care_index: 42.8,
    cost_of_living_index: 32.25,
    property_price_to_income_ratio: 13.1,
    pollution_index: 86.21,
    climate_index: 71.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    country: "Nigeria",
    quality_of_life_index: 55.65,
    purchasing_power_index: 13.52,
    health_care_index: 51.59,
    cost_of_living_index: 31,
    property_price_to_income_ratio: 16.7,
    pollution_index: 87.63,
    climate_index: 60.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
].map((data, i) => {
  data.id = i + 1;
  return data;
});
